config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
               path("ISA/", include("isa_poll.urls", namespace='isa_poll'), name="home"),
               # Django Admin, use {% url 'admin:index' %}
                  path(settings.ADMIN_URL, admin.site.urls), # User management
                  path("users/", include("digitale_esa.users.urls", namespace="users")),
                  path("accounts/", include("allauth.urls")), # Your stuff: custom urls includes go here
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [path("400/", default_views.bad_request, kwargs={"exception": Exception("Bad Request!")}, ),
        path("403/", default_views.permission_denied, kwargs={"exception": Exception("Permission Denied")}, ),
        path("404/", default_views.page_not_found, kwargs={"exception": Exception("Page not Found")}, ),
        path("500/", default_views.server_error), ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

digitale_esa/users/urls.py
from django.urls import path

from digitale_esa.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

isa_poll/urls.py
from django.urls import path, re_path
from django.views.generic import TemplateView
from . import views

app_name = "isa_poll"
urlpatterns = [
    path("", views.PollSelector.as_view(template_name="isa_poll/poll_selector.html"), name="poll selector"),
    path("result/<poll_result_id>/", views.PollComplete.as_view(template_name="isa_poll/poll_complete.html"), name="poll complete"),
]

digitale_esa/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """Default user for Digital ISA."""

    #: First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

isa_poll/models.py
from django.db import models
from django.db.models import Model, FileField, ManyToManyField
from ckeditor.fields import RichTextField


# Create your models here.
class Question(Model):
    rich_text = RichTextField()

    def __str__(self):
        return str(self.rich_text)


class TopicGroup(Model):
    name = models.CharField("Text", max_length=128)

    def __str__(self):
        return self.name


class Topic(Model):
    topic_group = models.ForeignKey(TopicGroup, on_delete=models.PROTECT, null=True, blank=True)
    name = models.CharField("Text", max_length=128)
    question_list = models.ManyToManyField(Question, blank=True, default=None)

    def __str__(self):
        return self.name


class Questioner(Model):
    name = models.CharField("Text", max_length=128)
    topic_list = models.ManyToManyField(Topic, blank=True, default=None)

    def __str__(self):
        return self.name


class QuestionerResult(Model):
    client_name = models.CharField("Client", max_length=128)
    author_name = models.CharField("Document author", max_length=128)
    date_created = models.DateTimeField(auto_now_add=True)
    date_last_edit = models.DateTimeField(auto_now=True)
    questioner = models.ForeignKey(Questioner, on_delete=models.PROTECT)

    def __str__(self):
        return f"{self.client_name} by {self.author_name} created at {self.date_created.date()} (last edit: {self.date_last_edit.date()})"


class Answer(Model):
    question = models.ForeignKey(Question, on_delete=models.PROTECT)
    plain_text = models.CharField("Text", max_length=2048, null=True, blank=True)
    rich_text = RichTextField(null=True, blank=True)
    media_file = FileField(null=True, blank=True)
    questioner_result = models.ForeignKey(QuestionerResult, on_delete=models.PROTECT)

    def __str__(self):
        return self.plain_text or self.rich_text or ''

digitale_esa/users/forms.py
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(admin_forms.UserCreationForm):
    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }

digitale_esa/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        return self.request.user.get_absolute_url()  # type: ignore [union-attr]

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

isa_poll/views.py
from django.db.models import Q
from django.shortcuts import render
from django.views.generic import TemplateView
from .models import Questioner, QuestionerResult, Answer, Topic, Question, TopicGroup


class PollSelector(TemplateView):

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["templates"] = Questioner.objects.all()
        context["template_results"] = QuestionerResult.objects.all()
        return context


class PollComplete(TemplateView):

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            questioner_result = QuestionerResult.objects.get(id=context['poll_result_id'])
            context['questioner_result'] = questioner_result
        except Exception:
            # TODO Improve this exception
            print('FIX ME NOW')
            return context

        questioner = questioner_result.questioner  # type:Questioner

        result = []

        for topic_group in TopicGroup.objects.all():
            for topic in questioner.topic_list.filter(topic_group=topic_group):
                for question in Question.objects.filter(topic=topic):
                    for answer in Answer.objects.filter(Q(question=question) & Q(questioner_result=questioner_result)):
                        data_row = {'topic_group': topic_group, 'topic': topic, 'question': question, 'answer': answer}
                        result.append(data_row)

        context['answers'] = result

        return context

digitale_esa/templates/base.html
{% load static i18n %}<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}Digital ISA{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Automatisiertes ESA">
    <meta name="author" content="Mike Talalaevskiy">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">

    {% block css %}
        <!-- Latest compiled and minified Bootstrap CSS -->
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
              crossorigin="anonymous">

        <!-- Your stuff: Third-party CSS libraries go here -->
        <!-- This file stores project-specific CSS -->
        <link href="{% static 'css/project.css' %}" rel="stylesheet">
    {% endblock %}
    <!-- Le javascript
    ================================================== -->
    {# Placed at the top of the document so pages load faster with defer #}
    {% block javascript %}
        <!-- Bootstrap JS and its dependencies-->
        <script defer src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
                integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
                crossorigin="anonymous"></script>
        <script defer src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
                integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
                crossorigin="anonymous"></script>
        <script defer src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
                integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
                crossorigin="anonymous"></script>

        <!-- Your stuff: Third-party javascript libraries go here -->

        <!-- place project specific Javascript in this file -->
        <script defer src="{% static 'js/project.js' %}"></script>

    {% endblock javascript %}

</head>

<body>

<div class="mb-1">
    <nav class="navbar navbar-expand-md navbar-light bg-light">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'home' %}">Digital ISA</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'isa_poll:poll selector' %}">ISA Tool</a>
                </li>
                {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        {# URL provided by django-allauth/account/urls.py #}
                        <a class="nav-link"
                           href="{% url 'users:detail' request.user.username %}">{% translate "My Profile" %}</a>
                    </li>
                    <li class="nav-item">
                        {# URL provided by django-allauth/account/urls.py #}
                        <a class="nav-link" href="{% url 'account_logout' %}">{% translate "Sign Out" %}</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        {# URL provided by django-allauth/account/urls.py #}
                        <a id="sign-up-link" class="nav-link"
                           href="{% url 'account_signup' %}">{% translate "Sign Up" %}</a>
                    </li>
                    <li class="nav-item">
                        {# URL provided by django-allauth/account/urls.py #}
                        <a id="log-in-link" class="nav-link"
                           href="{% url 'account_login' %}">{% translate "Sign In" %}</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>

</div>

<div class="container">

    {% if messages %}
        {% for message in messages %}
            <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endfor %}
    {% endif %}

    {% block content %}
        <p>Welcome to the internal webpage.</p>
        <br>
        <p>List of useful tools:</p>
        <ul>
            <li>
                <p><a href="{% url 'isa_poll:poll selector' %}">Digital ISA tool</a></p>
            </li>
        </ul>
    {% endblock content %}

</div> <!-- /container -->

{% block modal %}{% endblock modal %}

{% block inline_javascript %}
    {# Script tags with only code, no src (defer by default) #}
{% endblock inline_javascript %}
</body>
</html>

digitale_esa/templates/isa_poll/poll_complete.html
{% extends "base.html" %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="page-header">
                    <h1>
                        ISA Report for client "{{ questioner_result.client_name }}" <br>
                    </h1>
                    <h3>Written by {{ questioner_result.author_name }} at {{ questioner_result.date_last_edit }}</h3>
                    <br>
                </div>
                {% for answer in answers %}
                    <h3>{{ answer.topic }}</h3>
                    {#TODO: REMOVE SAFE TAG#}
                    <p>{{ answer.question}}:
                        {{ answer.answer }}</p>
                    {% endfor %}
            </div>
        </div>
    </div>
{% endblock content %}

digitale_esa/templates/isa_poll/poll_in_progress.html
{% extends "base.html" %}

    {% block content %}
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<div class="page-header">
				<h1>
					LayoutIt! <small>Interface Builder for Bootstrap</small>
				</h1>
			</div>
			<form role="form" class="form-inline">
				<div class="form-group">

					<label for="exampleInputEmail1">
						Email address
					</label>
					<input type="email" class="form-control" id="exampleInputEmail1" />
				</div>
				<div class="form-group">

					<label for="exampleInputPassword1">
						Password
					</label>
					<input type="password" class="form-control" id="exampleInputPassword1" />
				</div>
				<div class="form-group">

					<label for="exampleInputFile">
						File input
					</label>
					<input type="file" class="form-control-file" id="exampleInputFile" />
					<p class="help-block">
						Example block-level help text here.
					</p>
				</div>
				<div class="checkbox">

					<label>
						<input type="checkbox" /> Check me out
					</label>
				</div>
				<button type="submit" class="btn btn-primary">
					Submit
				</button>
			</form>
		</div>
	</div>
</div>
    {% endblock content %}

digitale_esa/templates/isa_poll/poll_selector.html
{% extends "base.html" %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="page-header">
                    <h1>
                        ISA Digital <br><small>Create your questioner or use a template</small>
                    </h1>
                    <br>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <h3>
                            Templates:
                        </h3>
                        <ul>
                            {% for template in templates %}
                                <li class="list-item">
                                    <a href="/admin/isa_poll/questioner/{{ template.id }}/change/">{{ template }}</a>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="col-md-4">
                        <h3>
                            Finished questionnaires:
                        </h3>
                        <ul>
                            {% for result in template_results %}
                                <li class="list-item">
                                    <a href="{% url 'isa_poll:poll complete' result.id %}">{{ result }}</a>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="col-md-4">
                        <h3>
                            Help section:
                        </h3>
                        <p>Here you can find a lot of interesting information about how to use templates or create new
                            ones</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

digitale_esa/templates/pages/home.html
{% extends "base.html" %}

digitale_esa/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.username }}</h2>
      {% if object.name %}
        <p>{{ object.name }}</p>
      {% endif %}
    </div>
  </div>

{% if object == request.user %}
<!-- Action buttons -->
<div class="row">

  <div class="col-sm-12">
    <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">My Info</a>
    <a class="btn btn-primary" href="{% url 'account_email' %}" role="button">E-Mail</a>
    <!-- Your Stuff: Custom user template urls -->
  </div>

</div>
<!-- End Action buttons -->
{% endif %}

</div>
{% endblock content %}

digitale_esa/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <h1>{{ user.username }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn btn-primary">Update</button>
      </div>
    </div>
  </form>
{% endblock %}